### ISSUE TITLE
meteo data download error

### ISSUE THREAD

**Issue by igianca** [hydrovorobey/Global_BROOK90#1]
running the code and i got this error:
' Error in `_f`(user = user, request = request) : 
  Request specification has to contain a "dataset" identifier. '
any suggestion?

**Comment by hydrovorobey** [comment]
hi, could you please specify which R and ecmwf lib versions are you using since I don't get such an error.
probable reason - old version, I constantly have make minor updates to code due to new 3d party lib updates. But release v.1.2 should work. At least on on both machines I'm using.

**Comment by igianca** [comment]
hello!! after libraries updating it seems working very well, it is now
downloading data. thanks a million
